### Generate Otp
POST http://localhost:3000/api/auth/otp/generate
content-type: application/json

{
  "phoneNumber": "226-883-1846"
}

### Logout an user
GET http://localhost:3000/api/auth/user/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWI5MDlkN2U0NGE3ZWI0NjRjMDY3NjEiLCJwaG9uZU51bWJlciI6IjIyNi04ODMtMTg0NiIsImlhdCI6MTcwNjYyNTQ5NSwiZXhwIjoxNzA5MjE3NDk1fQ.QuzK7H3edN5oTjeKjhUu-l284aHhhsD3_QgcM8IpAR0


### Verify Otp
POST http://localhost:3000/api/auth/otp/verify
content-type: application/json

{
  "phoneNumber": "226-883-1846",
  "otp":  "455779"
}

### Sign Up an user
POST http://localhost:3000/api/auth/user/signup
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWI5MDlkN2U0NGE3ZWI0NjRjMDY3NjEiLCJwaG9uZU51bWJlciI6IjIyNi04ODMtMTg0NiIsImlhdCI6MTcwNjcyNDQyMCwiZXhwIjoxNzA5MzE2NDIwfQ.E-73-dcpFINxVDhxA6GP5FqF3ycpM91desJVjmPRcXw

{
  "firstName": "Samuel",
  "lastName":  "Gelvez",
  "email":  "sgelvez@gmail.com"
}


### Get Current User
GET http://localhost:3000/api/auth
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWI5MDlkN2U0NGE3ZWI0NjRjMDY3NjEiLCJwaG9uZU51bWJlciI6IjIyNi04ODMtMTg0NiIsImlhdCI6MTcwNjcyNDQyMCwiZXhwIjoxNzA5MzE2NDIwfQ.E-73-dcpFINxVDhxA6GP5FqF3ycpM91desJVjmPRcXw

### Update User
PUT http://localhost:3000/api/auth/user/update
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWI5MDlkN2U0NGE3ZWI0NjRjMDY3NjEiLCJwaG9uZU51bWJlciI6IjIyNi04ODMtMTg0NiIsImlhdCI6MTcwNjcyNDQyMCwiZXhwIjoxNzA5MzE2NDIwfQ.E-73-dcpFINxVDhxA6GP5FqF3ycpM91desJVjmPRcXw

{
"firstName": "Nicolas",
"lastName":  "Caceres",
"email":  "ncaceres@gmail.com"
}
